[package]
name = "tkbsv"
version = "0.1.0"
authors = ["Dung Ph <dungph@zoho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icalendar = "0.9.0"
chrono = "0.4.13"
calamine = "0.16.1"
tide = "0.11.0"
async-std = { version = "1.6.0", features = ["attributes"] }
rand = "0.7.3"
