name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

    services:
          postgres:
            image: postgres:12
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: postgres
            ports:
              # will assign a random free host port
                - 5432:5432
            # needed because the postgres container does not provide a healthcheck
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      
    - uses: Swatinem/rust-cache@v1
      with:
        cache-on-failure: true
    
    - uses: actions/checkout@v2
    
    - uses: actions-rs/install@v0.1
      with:
        crate: sqlx-cli
    
    - name: Migrate
      run: sqlx migrate run
    
    - name: Check sqlx-data
      run: cargo sqlx prepare --check
    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
